"""empty message

Revision ID: 0f1e2e070918
Revises: 
Create Date: 2018-09-27 01:20:45.230047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f1e2e070918'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('desciption', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_name'), 'jobs', ['name'], unique=True)
    op.create_table('monitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_name'), 'monitor', ['name'], unique=True)
    op.create_table('builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobs_id', sa.Integer(), nullable=True),
    sa.Column('changes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changes_id'], ['changes.id'], ),
    sa.ForeignKeyConstraint(['jobs_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pretty_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pretty_name', sa.String(length=255), nullable=False),
    sa.Column('jobs_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jobs_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jobs_id')
    )
    op.create_table('required_jobs',
    sa.Column('monitor_id', sa.Integer(), nullable=True),
    sa.Column('jobs_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jobs_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitor.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('required_jobs')
    op.drop_table('pretty_jobs')
    op.drop_table('builds')
    op.drop_index(op.f('ix_monitor_name'), table_name='monitor')
    op.drop_table('monitor')
    op.drop_index(op.f('ix_jobs_name'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('changes')
    # ### end Alembic commands ###
